name: Hourly Tasks

on:
  schedule:
    # 毎時実行
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Export environment variables
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}" >> $GITHUB_ENV
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "SLACK_BOT_TOKEN_MINUTES=${{ secrets.SLACK_BOT_TOKEN_MINUTES }}" >> $GITHUB_ENV
          echo "SLACK_BOT_TOKEN_REVIEW=${{ secrets.SLACK_BOT_TOKEN_REVIEW }}" >> $GITHUB_ENV
          echo "SLACK_BOT_TOKEN_AGENDA=${{ secrets.SLACK_BOT_TOKEN_AGENDA }}" >> $GITHUB_ENV
          echo "PRIMARY_SHEET_ID=${{ secrets.PRIMARY_SHEET_ID }}" >> $GITHUB_ENV
          echo "DEFAULT_CHANNEL_ID=${{ secrets.DEFAULT_CHANNEL_ID }}" >> $GITHUB_ENV
          echo "DEFAULT_TIMEZONE=${{ secrets.DEFAULT_TIMEZONE }}" >> $GITHUB_ENV
          echo "CALENDAR_ID=${{ secrets.CALENDAR_ID }}" >> $GITHUB_ENV
          echo "WORKSPACE_DOMAINS=${{ secrets.WORKSPACE_DOMAINS }}" >> $GITHUB_ENV
          echo "REVIEW_USER_ID=${{ secrets.REVIEW_USER_ID }}" >> $GITHUB_ENV

      - name: Check and post minutes
        run: python -m src.check_and_post_minutes

      - name: Send hearing reminders
        run: python -m src.send_hearing_reminder

      - name: Send agenda reminders
        run: python -m src.send_agenda_reminder

      - name: Collect hearing responses
        run: python -m src.collect_hearing_responses

      - name: Collect review requests
        run: python -m src.collect_review_requests
