name: two_days_before_hearing

on:
  schedule:
    - cron: "0 1 * * 1-5"  # JST 10:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Export env
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}" >> $GITHUB_ENV
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "PRIMARY_SHEET_ID=${{ secrets.PRIMARY_SHEET_ID }}" >> $GITHUB_ENV
          echo "DEFAULT_CHANNEL_ID=${{ secrets.DEFAULT_CHANNEL_ID }}" >> $GITHUB_ENV
          echo "DRIVE_FOLDER_ID=${{ secrets.DRIVE_FOLDER_ID }}" >> $GITHUB_ENV
          echo "MEETING_KEY=${{ secrets.MEETING_KEY }}" >> $GITHUB_ENV
          echo "DEFAULT_TIMEZONE=${{ secrets.DEFAULT_TIMEZONE }}" >> $GITHUB_ENV
      - name: Post hearing prompts
        run: python -m src.post_hearing
        working-directory: ./ai-meeting-autopilot

